### ISSUE TITLE
Stuck in bootloader

### ISSUE THREAD

**Issue by irmas5** [anestisb/android-prepare-vendor#177] opened 2020-11-01 11:58 UTC
Hi. I hard bricked a pixel 2xl. i'm stuck in bootloader with no os and no recovery, when i locked back bootloader they wiped all system and recovery. Maybe here are some way how to fix? Thank you

**Comment by thestinger** [comment] 2020-11-01 13:32
You should ask on the #grapheneos IRC / Matrix channel. You should probably just unlock the device and flash again.

**Comment by thestinger** [comment] 2020-11-01 13:32
You should probably just unlock the device and flash again. You should also use android-prepare-vendor from AOSP Alliance which is being actively developed.

**Comment by irmas5** [comment] 2020-11-01 15:12
I can't flash anything becouse i don't have recovery, when i trying fastboot image file for a pixel 2xl saying failed flash in locked state.

**Comment by thestinger** [comment] 2020-11-01 15:16
Recovery isn't where you flash images. Unlock the bootloader.

**Comment by irmas5** [comment] 2020-11-01 16:58
How, if I can't flash in fastboot? Saying failed flash in a locked state

**Comment by thestinger** [comment] 2020-11-01 17:03
> Unlock the bootloader.

**Comment by thestinger** [comment] 2020-11-01 17:04
Not going to try helping further because you aren't listening.

**Comment by irmas5** [comment] 2020-11-01 17:06
Sorry, I'm really not a tech, and I don't know how to fix that. I', now without a phone.

**Comment by thestinger** [comment] 2020-11-01 17:07
The issue is that you aren't listening. Read what I wrote. No point in a conversation if you don't read what I write.

**Comment by irmas5** [comment] 2020-11-01 17:08
I reading. Unlock bootloader. Just how? Can you help me?

**Comment by thestinger** [comment] 2020-11-01 17:09
The opposite of locking it which is what you said you did at the start...

**Comment by thestinger** [comment] 2020-11-01 17:10
You need to do your own research. I don't think filing an issue here makes my sense. I suggest closing it and reading about this.

**Comment by irmas5** [comment] 2020-11-01 17:15
I searched on xda, Reddit. Nowhere found how to unlock bootloader from the fastboot menu.

**Comment by thestinger** [comment] 2020-11-01 17:26
The opposite of locking the bootloader: unlock instead of lock.

**Comment by irmas5** [comment] 2020-11-01 17:46
I tried, but showing ...
FAILED (remote: unknown command)
finished. total time: 0.006s
PS C:\adb> fastboot flashing unlock
...
FAILED (remote: Flashing Unlock is not allowed
)
finished. total time: 0.016s

**Comment by irmas5** [comment] 2020-11-01 17:47
PS C:\adb> fastboot flashing unlock_critical
...
FAILED (remote: Flashing Unlock is not allowed
)
finished. total time: 0.007s

**Comment by thestinger** [comment] 2020-11-01 17:47
Did you disable OEM unlocking in the OS?

**Comment by irmas5** [comment] 2020-11-01 17:51
I can't enter to os.
![123201924_1948346391972058_1246145758924499473_n](https://user-images.githubusercontent.com/73780406/97810307-d7f1ef00-1c6a-11eb-9f28-2beb2622e173.jpg)
![123086075_392913548785602_7858981799469812014_n](https://user-images.githubusercontent.com/73780406/97810309-da544900-1c6a-11eb-9316-a8c184cd7b09.jpg)

**Comment by irmas5** [comment] 2020-11-01 17:53
After I relocked the bootloader I think wiped all partition, os, and recovery.

**Comment by irmas5** [comment] 2020-11-01 17:53
I was on custom rom.

**Comment by irmas5** [comment] 2020-11-01 17:54
In oem was switched of.

**Closed as completed** 2020-11-02 00:18 UTC
