### ISSUE TITLE
marlin/sailfish flashlight quick settings icon greyed out after first boot of an update

### ISSUE THREAD

**Issue by thestinger** [anestisb/android-prepare-vendor#58] opened 2017-02-11 20:56 UTC
I am pretty sure this is caused by missing something in AOSP / android-prepare-vendor. It might have another local cause though, so it would be good if someone could confirm that they hit this.

**Comment by anestisb** [comment] 2017-02-11 21:15
Issue has been confirmed. After a hardware reboot, the flashlight icon grays-out and cannot be enabled.

I'll investigate the issue.

**Comment by thestinger** [comment] 2017-02-11 21:17
It's quite weird since the camera and camera flash still work.

**Comment by anestisb** [comment] 2017-02-12 10:52
After a factory reset the flashlight is working fine until the next reboot. It seems that there is some kind of post-boot configuration that conflicts or destroys some assets access of the CameraService. I'm still investigating, although evidence so far indicate that is not a missing blob. Seems some kind of configuration conflict (probably against data stored under /data).

**Comment by mke208** [comment] 2017-02-12 16:33
Just noticed something regarding this issue: if you remove the flashlight widget and then re-add it, it starts working ...  Device is marlin.

**Comment by anestisb** [comment] 2017-02-12 17:21
It seems some kind of race condition, since `CameraManagerGlobal` service is requesting resources from `CameraService` service before the latter has finished initialization. It seems to try two times (probably one for each cameraID - front and back) and then abort, leaving some runtime objects null.

```
05-22 11:59:53.749  1396  1396 I CameraManagerGlobal: Connecting to camera service
05-22 11:59:53.749  1396  1396 E CameraManagerGlobal: Camera service is unavailable
05-22 11:59:53.780  1396  1396 I CameraManagerGlobal: Connecting to camera service
05-22 11:59:53.780  1396  1396 E CameraManagerGlobal: Camera service is unavailable
```

As such I don't think the issue is related to the vendor blobs.

**Comment by anestisb** [comment] 2017-02-12 18:13
Attaching camera logs vs factory

[aosp_camera_log.txt](https://github.com/anestisb/android-prepare-vendor/files/769506/aosp_camera_log.txt)
[factory_camera_log.txt](https://github.com/anestisb/android-prepare-vendor/files/769507/factory_camera_log.txt)

It's quite clear that `CameraManagerGlobal` is not blocking until `CameraService` has completed initialization. Issue should be reported to upstream as it doesn't appear to be connected to vendor blobs.

**Comment by thestinger** [comment] 2017-02-12 20:03
Does this happen with stock though? Maybe they aren't using the AOSP code...

**Comment by anestisb** [comment] 2017-02-12 20:27
The `CameraManagerGlobal` code from AOSP appears to be identical between AOSP and factory images. However, I don't know which component or configuration value is triggering the problem in AOSP builds but not factory. It might be related to the actual camera app and the native libraries it deploys, although it's hard to confirm since the app implements lots of functionality.

**Comment by thestinger** [comment] 2017-02-22 01:26
Removing the flashlight quick tile and adding it back works around it. It's weird, because it seems to try to register a callback to be notified when this service is available: https://developer.android.com/reference/android/hardware/camera2/CameraManager.html#registerTorchCallback(android.hardware.camera2.CameraManager.TorchCallback, android.os.Handler). It seems the service itself is somehow unavailable...

**Comment by thestinger** [comment] 2017-02-22 03:26
Alright I did a partial workaround for this so that it at least starts working once it's touched (assuming camera service is loaded by then): https://github.com/CopperheadOS/platform_frameworks_base/commit/79ea29c5205ed6a2a923a8a4f6aaf7f935274724. Before then it's greyed out. It really needs to wait until the service is ready, but I'm not sure how to do that at the moment if it's even possible without deeper surgery.

**Comment by thestinger** [comment] 2017-02-25 10:52
I think one of our users hit this on the Nexus 5X: https://github.com/copperhead/bugtracker/issues/597#issuecomment-282476247. I'm glad to have added that recovery hack because it adds some robustness against this kind of failure. I'd like to solve it properly and upstream that though...

**Comment by vamsirocks** [comment] 2017-03-31 10:10
Hi i need help how to build pixel aosp without including recovery partition, such that device cant enter recovery mode

**Comment by thestinger** [comment] 2017-03-31 15:08
I don't think that has anything to do with this...

**Comment by anestisb** [comment] 2017-04-01 08:05
@vamsirocks please open a different issue since what you're asking is not related to this thread.

**Comment by anestisb** [comment] 2017-05-13 12:24
I think that the issue has been fixed in upstream AOSP. Just tested a NHG47L android-7.1.2_r11 sailfish build and the flashlight appears to work fine across device reboots.

**Closed** 2017-05-18 09:20 UTC
Labels: device support
